repo_root <- normalizePath(file.path("..", ".."), mustWork = TRUE)
.libPaths(c(file.path(repo_root, ".Rlib"), .libPaths()))

source(file.path(repo_root, "R", "rocdata.R"))
source(file.path(repo_root, "R", "mROC.R"))
source(file.path(repo_root, "R", "pAUC.R"))
source(file.path(repo_root, "R", "status_utils.R"))
source(file.path(repo_root, "R", "data_input_utils.R"))
source(file.path(repo_root, "R", "shared_state.R"))
source(file.path(repo_root, "R", "mod_downloads.R"))
source(file.path(repo_root, "R", "printCutOff.R"))
